dataset:
    name: imagenet
    root: ~/datasets/ILSVRC2012
    n_classes: 1000

training:
    optimizer:
        name: SGD
        lr: 0.1
        weight_decay: 1.0e-4
        momentum: 0.9
    lr_schedule:
        name: multi_step
        milestones: [150000, 300000]
        gamma: 0.1
        # warmup_iters: 300
        # warmup_mode: linear
        # warmup_factor: 0.3333
    train_iters: 450000
    print_interval: 50
    val_interval: 2000
    batch_size: 256
    num_workers: 16
    sync_bn: True

validation:
    batch_size: 256
    num_workers: 16

model:
    name: ResNet50

